import Head from 'next/head'
import CounterJson from "../data/counter_milestones.json"
import ChooseJson from "../data/choose_us.json"
import Footer from "../components/Footer"

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='home'>
        {/* jumbotron or bulletin */}
        <div id='bulletin' className="p-0 text-center bg-image rounded-3" >
          <div className="mask">
            <div className="d-flex justify-content-center align-items-center h-100">
              <div className="text-white pull-right">
                <h1 className="mb-3">S.E. (Sem III) - T.E. (SEM V)</h1>
                <h3 className="mb-3">Regular batches starting from 25 August</h3>
                {/* <a className="btn btn-outline-info " href="#!" role="button">Generate Your List</a> */}
              </div>
            </div>
          </div>
        </div>

        {/* counter */}
        <div className='row border px-3 m-0 counter-row justify-content-center'>
          {
            CounterJson.map((counter, index) => {
              const setTimersClass = `timer${index} counter-desc`
              return (
                <div key={index} className="col-lg-3 col-md-6 col-sm-12 p-1 m-0 text-center">
                  <div className="milestone-container">
                    <img className='milestone' src={counter.icon} />
                  </div>
                  <br />
                  <span className={setTimersClass}></span>
                  <p className='counter-desc'>{counter.sign}</p>
                  <p className='counter-p'>{counter.desc}</p>
                </div>
              )
            })
          }
        </div>

        <div className='container'>
          {/* About Us and Text */}
          <div className='row about-row text-center'>
            <div className='col-lg-4 col-md-6 col-sm-12 about-left'>
              <h1 className='about-title'>About Us</h1>
            </div>
            <div className='col-lg-8 col-md-6 col-sm-12 '>
              <p className='lead text-justify'>
                Engineering Minds comprises a team of teachers having seamless wealth of knowledge and insurmountable experience. The expertise of these teachers and their unique teaching techniques has helped thousands of students achieve meritorious marks in their exams. Every teacher of our team has experience of 20+ years and has taught 15000+ engineering students in their respective careers. Our endeavor is to excel in everything we do. We are currently offering offline coaching in Borivali and Mulund.
              </p>
            </div>
          </div>

          {/* why choose us */}
          <div className="row">
            <div className='col-12'>
              <div className="team-boxed">
                <div className="container">
                  <div className="intro w-100">
                    <h2 className="text-center">
                    Why Choose <span>engineering minds</span> ?
                    </h2>
                  </div>
                  <div className="row people">
                    {
                      ChooseJson.map((choose, index) => {
                        return (
                          <div key={index} className="col-lg-4 col-md-6 col-sm-12  item">
                            <div className="box">
                              <img className="img-responsive" src={choose.icon} />
                              <h4 className="name" style={{ color: "black" }}>{choose.title}</h4>
                              <p className="title"></p>
                              <p className="description">{choose.desc}</p>
                              <div className="social"></div>
                            </div>
                          </div>
                        )
                      })
                    }
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <Footer />

      </div>
    </div>
  )
}
